#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use Console\Commands\CreateControllerCommand;

$app = new Application();
$app->add(new CreateControllerCommand());
$app->run();
